name: taiko

on:
  push:
  pull_request:
    branches:
      - master

jobs:
  functional-tests-windows:
    name: FTs - NodeJS 22 & windows-latest (run ${{ matrix.run }})
    runs-on: windows-latest
    strategy:
      matrix:
        run: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
      fail-fast: false
    steps:
      - uses: actions/checkout@v6
      - name: Use NodeJS 22
        uses: actions/setup-node@v6
        with:
          node-version: '22'
          check-latest: 'true'
      - name: install
        run: npm ci
      - name: functional-tests (windows)
        env:
          DEBUG: taiko:intercept
        run: npm run test-functional

      - name: Upload html report
        uses: actions/upload-artifact@v6
        if: failure()
        with:
          name: ft-reports-windows-run${{ matrix.run }}
          path: tests/functional-tests/reports/html-report

      - name: Upload logs
        uses: actions/upload-artifact@v6
        if: failure()
        with:
          name: ft-logs-windows-run${{ matrix.run }}
          path: tests/functional-tests/logs
